version: '3.3'

services:
  fakewitter_db:
    image: postgres
    environment:
      - POSTGRES_USER=fakewitter
      - POSTGRES_PASSWORD=f4k3w1773r
      - POSTGRES_DB=fakewitter_db

  fakewitter:
    build: .
    volumes:
      - .:/code
    ports:
      - 3333:3333
    links:
      - fakewitter_db
    depends_on:
      - fakewitter_db
